network:
  rpc: ""
  verifier_address: ""
  vault_address: "http://127.0.0.1:8200"
  vault_mount_path: "secret_data"

log:
  level: debug
  disable_sentry: true

db:
  url: db_url

listener:
  addr: :8000

cop:
  disabled: true
  endpoint: "http://..."
  upstream: "http://..."
  service_name: proof-verification-relayer
  service_port: 80
