network:
  rpc: "https://rpc.evm.mainnet.rarimo.com/"
  vault_address: "http://127.0.0.1:8200"
  vault_mount_path: "secret_data"
  gas_multiplier: 1.23
  private_key: without '0x' # For security purposes this key may be omitted and flow with Vault would be used

contracts:
  proposer:
    address: null
  voting_registry:
    address: null
  lightweight_state:
    address: null
  register2:
    address: "0xA25a197d26Cad659A8fFf7F268cA4F9e0283de03"
    block: 4939333 # Block is optional field for contract listeners, default value is 0 if nothing set

log:
  level: debug
  disable_sentry: true

db:
  url: db_url

pinger:
  blocks_distance: 10000
  timeout: 5s # timeout to ping logs when 'subscribed' via http
  normal_period: 10s
  min_abnormal_period: 10s
  max_abnormal_period: 10s

replicator:
  source_smt: 0xc1534912902BBe8C54626e2D69288C76a843bc0E
  root_prefix: Rarimo root

listener:
  addr: :8000

cop:
  disabled: true
  endpoint: "http://..."
  upstream: "http://..."
  service_name: proof-verification-relayer
  service_port: 80
